"""Morning reconciliation report for the finance team: daily summary table,
active alerts, and a CSV of every unmatched/suspect transaction to work through.
"""

from __future__ import annotations

from decimal import Decimal

from pipelines.orders.common import REPO_ROOT, connect, get_logger

log = get_logger("recon.report")

MD_PATH = REPO_ROOT / "reports" / "recon_summary.md"
CSV_PATH = REPO_ROOT / "reports" / "recon_unmatched.csv"

FOLLOW_UP_BUCKETS = (
    "missing_in_ledger", "missing_in_gateway", "amount_other",
    "possible_ref_issue", "duplicate_posting",
)


def _fmt(v) -> str:
    if isinstance(v, (float, Decimal)):
        return f"{v:,.2f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def _md_table(headers: list[str], rows: list[tuple]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(_fmt(v) for v in row) + " |" for row in rows]
    return "\n".join(lines)


def main() -> None:
    con = connect(read_only=True)
    summary = con.execute("""
        SELECT txn_date, gateway_count, ledger_count, matched,
               fee_timing, rounding, amount_other, possible_ref_issue,
               missing_in_ledger, missing_in_gateway, duplicate_posting,
               match_rate_pct, ROUND(net_difference, 2)
        FROM recon.recon_summary ORDER BY txn_date""").fetchall()
    alerts = con.execute(
        "SELECT txn_date, severity, rule, detail FROM recon.alerts ORDER BY txn_date, severity"
    ).fetchall()

    con.execute(f"""
        COPY (
            SELECT * FROM recon.recon_results
            WHERE match_type IN {FOLLOW_UP_BUCKETS}
            ORDER BY txn_date, match_type, ref
        ) TO '{CSV_PATH}' (HEADER, DELIMITER ',')
    """)
    n_follow_up = con.execute(
        f"SELECT count(*) FROM recon.recon_results WHERE match_type IN {FOLLOW_UP_BUCKETS}"
    ).fetchone()[0]
    con.close()

    parts = [
        "# Reconciliation Summary — gateway vs ledger",
        "",
        "_Auto-generated by `pipelines/reconciliation/report.py`. Amounts in THB._",
        "",
        "## Daily results",
        "",
        _md_table(
            ["Date", "Gateway", "Ledger", "Matched", "Fee timing", "Rounding",
             "Amount other", "Ref issue?", "Missing in ledger", "Missing in gateway",
             "Dup posting", "Match %", "Net diff"],
            summary,
        ),
        "",
        "## Active alerts",
        "",
        _md_table(["Date", "Severity", "Rule", "Detail"], alerts) if alerts else "_none_",
        "",
        f"## Follow-up queue: {n_follow_up:,} records → `reports/recon_unmatched.csv`",
        "",
        "Bucket definitions and the matching waterfall live in",
        "`pipelines/reconciliation/README.md`.",
        "",
    ]
    MD_PATH.parent.mkdir(parents=True, exist_ok=True)
    MD_PATH.write_text("\n".join(parts))
    log.info("wrote %s and %s (%d follow-ups)", MD_PATH, CSV_PATH, n_follow_up)


if __name__ == "__main__":
    main()
