"""Marketing summary for the growth team: channel scoreboard, cross-platform
campaign rollup, blended ROAS, and the data-quality notes that change how much
to trust today's numbers (late files, missing conversions).
"""

from __future__ import annotations

from decimal import Decimal

from pipelines.orders.common import REPO_ROOT, connect, get_logger

log = get_logger("marketing.report")

OUT_PATH = REPO_ROOT / "reports" / "marketing_summary.md"


def _fmt(v) -> str:
    if isinstance(v, (float, Decimal)):
        return f"{v:,.2f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v) if v is not None else "—"


def _md_table(headers: list[str], rows: list[tuple]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(_fmt(v) for v in row) + " |" for row in rows]
    return "\n".join(lines)


def main() -> None:
    con = connect(read_only=True)
    q = lambda sql: con.execute(sql).fetchall()  # noqa: E731

    channels = q("""
        SELECT platform,
               ROUND(SUM(spend_thb), 2),
               SUM(attributed_orders),
               ROUND(SUM(attributed_revenue_thb), 2),
               ROUND(SUM(attributed_revenue_thb) / NULLIF(SUM(spend_thb), 0), 2) AS roas
        FROM marts.fct_channel_performance
        GROUP BY platform ORDER BY roas DESC NULLS LAST""")
    campaigns = q("""
        SELECT canonical, n_platforms, ROUND(spend_thb, 2), attributed_orders,
               ROUND(attributed_revenue_thb, 2), roas
        FROM marts.fct_campaign_performance
        ORDER BY roas DESC NULLS LAST""")
    blended = q("""
        SELECT ROUND(SUM(spend_thb), 2),
               ROUND(SUM(attributed_revenue_thb), 2),
               ROUND(SUM(attributed_revenue_thb) / NULLIF(SUM(spend_thb), 0), 2)
        FROM marts.fct_channel_performance WHERE platform != 'organic'""")[0]

    missing_files = q("""
        WITH expected AS (SELECT DISTINCT report_date, 'tiktok' AS platform
                          FROM staging.stg_ad_performance),
             loaded AS (SELECT DISTINCT report_date, platform
                        FROM staging.stg_ad_performance WHERE platform = 'tiktok')
        SELECT e.report_date FROM expected e
        LEFT JOIN loaded l USING (report_date, platform)
        WHERE l.report_date IS NULL ORDER BY 1""")
    na_conversions = q("SELECT count(*) FROM staging.stg_ad_performance WHERE conversions_missing")[0][0]
    con.close()

    late_note = (
        f"TikTok file(s) not yet delivered for: {', '.join(str(r[0]) for r in missing_files)} "
        "— spend for those days is understated until backfill."
        if missing_files else "All platform files delivered for all loaded dates."
    )

    parts = [
        "# Marketing Summary — spend vs attributed revenue",
        "",
        "_Auto-generated by `pipelines/marketing/report.py`. Amounts in THB;_",
        "_attribution is last-touch on the order's UTM — see the pipeline README_",
        "_for what that deliberately over- and under-counts._",
        "",
        "## Blended (paid channels only)",
        "",
        _md_table(["Total spend", "Attributed revenue", "Blended ROAS"], [blended]),
        "",
        "## By channel",
        "",
        _md_table(["Platform", "Spend", "Attributed orders", "Attributed revenue", "ROAS"], channels),
        "",
        "## By campaign (cross-platform canonical)",
        "",
        _md_table(["Campaign", "Platforms", "Spend", "Orders", "Revenue", "ROAS"], campaigns),
        "",
        "## Data quality notes",
        "",
        f"- {late_note}",
        f"- {na_conversions} ad rows report conversions as \"N/A\" — their spend is",
        "  counted, their platform-conversion column is not.",
        "- `organic` rows carry revenue with zero spend by definition; blended ROAS",
        "  excludes them.",
        "",
    ]
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(parts))
    log.info("wrote %s", OUT_PATH)


if __name__ == "__main__":
    main()
