"""Produce the daily business summary (markdown) the way an analyst would
receive it every morning: 30-day sales, category/channel breakdowns, refund
behaviour, and an honest account of what was rejected and why.
"""

from __future__ import annotations

from decimal import Decimal

from pipelines.orders.common import REPO_ROOT, connect, get_logger

log = get_logger("report")

OUT_PATH = REPO_ROOT / "reports" / "sales_summary.md"


def _md_table(headers: list[str], rows: list[tuple]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for row in rows:
        lines.append("| " + " | ".join(_fmt(v) for v in row) + " |")
    return "\n".join(lines)


def _fmt(v) -> str:
    if isinstance(v, (float, Decimal)):
        return f"{v:,.2f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def build_report() -> str:
    con = connect(read_only=True)
    q = lambda sql: con.execute(sql).fetchall()  # noqa: E731

    period = q("SELECT min(business_date), max(business_date) FROM marts.fct_daily_sales")[0]
    money = q("""
        SELECT SUM(net_amount), SUM(gross_amount), SUM(refund_amount)
        FROM marts.fct_daily_sales""")[0]
    counts = q("SELECT SUM(net_orders), SUM(refunded_orders) FROM marts.fct_daily_orders")[0]
    net, gross, refund = (float(money[0]), float(money[1]), float(money[2]))
    orders, refunded = int(counts[0]), int(counts[1])

    daily = q("""
        SELECT s.business_date, o.net_orders, ROUND(s.net_amount, 2), ROUND(s.refund_amount, 2)
        FROM (SELECT business_date, SUM(net_amount) AS net_amount, SUM(refund_amount) AS refund_amount
              FROM marts.fct_daily_sales GROUP BY 1) s
        JOIN (SELECT business_date, SUM(net_orders) AS net_orders
              FROM marts.fct_daily_orders GROUP BY 1) o USING (business_date)
        ORDER BY 1""")
    categories = q("""
        SELECT category, ROUND(SUM(net_amount), 2) AS net
        FROM marts.fct_daily_sales GROUP BY 1 ORDER BY net DESC""")
    channels = q("""
        SELECT channel, SUM(net_orders), ROUND(SUM(net_amount), 2)
        FROM marts.fct_daily_orders GROUP BY 1 ORDER BY 3 DESC""")
    refunds = q("SELECT * FROM marts.fct_refund_analysis")
    rejected = q("""
        SELECT reject_reason, count(*) FROM staging.rejected_orders
        GROUP BY 1 ORDER BY 2 DESC""")
    con.close()

    parts = [
        f"# Sales Summary — {period[0]} to {period[1]}",
        "",
        "_Auto-generated by `pipelines/orders/report.py`. Amounts in THB._",
        "",
        "## Headline",
        "",
        _md_table(
            ["Net revenue", "Gross", "Refunded", "Net orders", "Refunded orders", "Refund rate"],
            [(net, gross, refund, orders, refunded, f"{refunded / (orders + refunded) * 100:.2f}%")],
        ),
        "",
        "## Net revenue by category",
        "",
        _md_table(["Category", "Net revenue"], categories),
        "",
        "## Channel performance",
        "",
        _md_table(["Channel", "Net orders", "Net revenue"], channels),
        "",
        "## Refund analysis by category",
        "",
        _md_table(["Category", "Paid orders", "Refunded", "Refund rate %", "Refunded amount"], refunds),
        "",
        "## Daily trend",
        "",
        _md_table(["Date", "Net orders", "Net revenue", "Refunded amount"], daily),
        "",
        "## Rejected records (quarantined, never silently dropped)",
        "",
        _md_table(["Reason", "Rows"], rejected),
        "",
        "See `pipelines/orders/example_queries.sql` for the analyst query pack.",
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(build_report())
    log.info("wrote %s", OUT_PATH)


if __name__ == "__main__":
    main()
